accounts/urls.py
from django.urls import path
from .views import signup, login, notloginmy, logout, my

app_name='accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('my/notlogin', notloginmy, name='notloginmy'),
    path('my/<int:user_id>', my, name='my'),
]

buket/urls.py
from django.urls import path
from .views import buket, buy, share

app_name='buket'

urlpatterns = [
    path('', buket, name='buket'),
    path('share/', share, name='share'),
    path('buy/', buy, name='buy'),
]

busket/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('buket/', include('buket.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home,landing

app_name='home'

urlpatterns = [
    path('home/', home, name='home'),
    path('', landing, name='landing'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>BUSKET</title>
</head>

<body style="background-image:url({% static 'img/background.svg' %})">
    <div class="wrap">
        <header/Scripts/activate class="main-header">
            <div class="logo">
                <a href="/">
                <img src="{% static 'img/logo.svg' %}" alt="logo"/>
            </a>
            </div>
            <ul class="category">
                <li class="home"><a href="{% url 'home:home' %}">HOME</a></li>
                <li class="buy"><a href="{% url 'buket:buy' %}">BUY</a></li>
                <li class="bucket"><a href="{% url 'buket:buket' %}">BUCKET</a></li>
                {% if user.is_authenticated %}
                <li class="my"><a href="{% url 'accounts:my' user.id %}">MY</a></li>
                {%else%}
                <li class="my"><a href="{% url 'accounts:notloginmy' %}">MY</a></li>
                {%endif%}
            </ul>
        </header>
        
            {% block content %}

            {% endblock %}
        
            <footer class="main-footer">
                <div class="inner">
                    <p>ⓒ SSWU_WAGI 2기 Team.WEB</p>
                    <p class="member">BACKEND 조수빈 손정민 <br /> FRONTEND 최수진 백수진 이가윤 이예솔</p>
                </div>
            </footer>

    </div>
</body>

</html>

templates/base_test.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>BUSKET</title>
</head>

<body style="background-image:url({% static 'img/background.svg' %})">
    <div class="wrap">
        <header class="main-header">
            <div class="logo">
                <a href="/">
                <img src="{% static 'img/logo.svg' %}" alt="logo"/>
            </a>
            </div>
            <ul class="category">
                <li class="buy">BUY</li>
                <li class="bucket">BUCKET</li>
                <li class="share">SHARE</li>
                {% comment %} 로그인 되어있을 때와 로그아웃 되어있을 때 MY 버튼 다르게 설정(보이는 건 같음) {% endcomment %}
                {% if user.is_authenticated %}
                <li class="my"><a href="{% url 'accounts:my' user.id %}">MY</a></li>
                {%else%}
                <li class="my">MY</li>
                {%endif%}
            </ul>
        </header>
        <main>
            {% block content %}

            {% endblock %}
        </main>

        <footer class="main-footer">
            <div class="inner">
                <p>ⓒ SSWU_WAGI 2기 Team.WEB</p>
                <p class="member">BACKEND 조수빈 손정민 <br /> FRONTEND 최수진 백수진 김가윤</p>
            </div>
        </footer>
    </div>
</body>

</html>